
const deviceByModel = {
    iPhone: [
        'iPhone XR',
        'iPhone XS',
        'iPhone XS Max',
        'iPhone 11',
        'iPhone 11 Pro',
        'iPhone 11 Pro Max',
        'iPhone SE 2 (2020)',
        'iPhone 12',
        'iPhone 12 Mini',
        'iPhone 12 Pro',
        'iPhone 12 Pro Max',
        'iPhone 13',
        'iPhone 13 Mini',
        'iPhone 13 Pro',
        'iPhone 13 Pro Max',
        'iPhone SE 3 (2022)',
        'iPhone 14',
        'iPhone 14 Plus',
        'iPhone 14 Pro',
        'iPhone 14 Pro Max',
        'iPad Pro 11″ (model A2068, from 2020)',
        'iPad Pro 12.9″ (model A2069, from 2020)',
        'iPad Air (model A2123, from 2019)',
        'iPad (model A2198, from 2019)',
        'iPad Mini (model A2124, from 2019)',
        'IPad 10th generación (modelo 2022)',
    ],
    Android: [
        'AQUOS wish 2 SHG08',
        'AQUOS wish3',
        'AQUOS zero 6',
        'Google Pixel 3a XL',
        'Google Pixel 4',
        'Google Pixel 4a',
        'Google Pixel 4 XL',
        'Google Pixel 5',
        'Google Pixel 5a',
        'Google Pixel 6',
        'Google pixel 6a',
        'Google Pixel 6 Pro',
        'Google Pixel 7',
        'Google Pixel 7 Pro',
        'Google Pixel Fold',
        'Huawei P40',
        'Huawei P40 Pro',
        'Huawei Mate 40 Pro',
        'Motorola Razr 2019',
        'Motorola Razr 5G',
        'Motorola Razr 40',
        'Motorola Razr 40 Ultra',
        'Motorola Razr+',
        'Motorola Edge+',
        'Motorola Edge 40 Pro',
        'Motorola G52J 5G',
        'Motorola G52J 5G Ⅱ',
        'Motorola G53J 5G',
        'Nokia XR21',
        'Nokia X30',
        'Nokia G60 5G',
        'Oppo Find X3 Pro',
        'Oppo Reno 5A',
        'Oppo Reno 6 Pro 5G',
        'Oppo Find X5',
        'Oppo Find X5 Pro',
        'Oppo A55s 5G',
        'Rakuten Mini',
        'Rakuten Big-S',
        'Rakuten Big',
        'Rakuten Hand',
        'Rakuten Hand 5G',
        'Samsung Galaxy A54 5G',
        'Samsung Galaxy S20',
        'Samsung Galaxy S20+',
        'Samsung Galaxy S20+ 5g',
        'Samsung Galaxy S20 Ultra',
        'Samsung Galaxy S20 Ultra 5G',
        'Samsung Galaxy S21',
        'Samsung Galaxy S21+ 5G',
        'Samsung Galaxy S21+ Ultra 5G',
        'Samsung Galaxy S22',
        'Samsung Galaxy S22+',
        'Samsung Galaxy S22 Ultra',
        'Samsung Galaxy S23',
        'Samsung Galaxy S23+',
        'Samsung Galaxy S23 Ultra',
        'Samsung Galaxy Note 20',
        'Samsung Galaxy Note 20 Ultra 5G ',
        'Samsung Galaxy Fold',
        'Samsung Galaxy Z Fold2 5G',
        'Samsung Galaxy Z Fold3 5G',
        'Samsung Galaxy Z Fold4',
        'Samsung Galaxy Z Fold5 5G',
        'Samsung Galaxy Z Flip',
        'Samsung Galaxy Z Flip3 5G',
        'Samsung Galaxy Z Flip4',
        'Samsung Galaxy Z Flip5 5G',
        'Sony Xperia 10 III Lite',
        'Sony Xperia 10 IV',
        'Sony Xperia 5 IV',
        'Sony Xperia 1 V',
        'Sony Xperia Ace III',
        'Sharp AQUOS sense4 lite',
        'Sharp AQUOS Sense6s',
        'Simple Sumaho6',
        'Sharp AQUOS R7',
        'Sharp AQUOS R8',
        'Sharp AQUOS R8 Pro',
        'Surface Pro X',
        'Vivo X90 Pro',
        'Xperia 10V',
        'Xperia 1 IV',
        'Xiaomi 12T Pro',
        'Xiaomi 13',
        'Xiaomi 13 Lite',
        'Xiaomi 13 Pro',
    ],
    // Add more countries and their states as needed
};

export default deviceByModel;
